### ISSUE TITLE
Question: What's at VU unlike Whitecore Sims?

### ISSUE THREAD

**Issue by BogusCurry** [Virtual-Universe/Virtual-Universe#10]
Hello ;D

I see for mounth, that here make a another Virtual Simulation, but what about VU ? Is a another concept or what ?

**Comment by emperorstarfinder** [comment]
Hi there,

Virtual Universe will be a planetary based grid.  This means the current modern day regions will be turned into planets.  The abilities that aren't able to be performed on region based architectures will be able to be performed on the planets.  There will be features that will be different and some features will be familiar to everyone.  Virtual-Universe however will maintain compatibility with WhiteCoreSim as has been decided by the development team to allow users of WhiteCoreSim to easily add a planetary based architecture and offer both.  This also means that once hypergrid is implemented users on a WhiteCore-Sim based grid will be able to teleport to a Virtual-Universe based planet.  We will have a full features documentation available shortly.

Emperor Starfinder
CEO
Core Developer
Grid Architecture Development
Second Galaxy Development Team

**Comment by BogusCurry** [comment]
Thanks for the fast answer ;D The sounds like good and is very intressest ;D Maybe we talk sometimes in a grid or so ;D

Greetings

Bogus

**Comment by emperorstarfinder** [comment]
We are always able to be contacted on IRC on Freenode in #galaxyfutures which is our irc support channel.

Emperor Starfinder
CEO
Core Developer
Grid Architecture Development
Second Galaxy Development Team
