### ISSUE TITLE
bag

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#12]
After making changes to the server today is not fully compiled. As if to make changes in the WebUI and compile the new as there are no changes. http://prntscr.com/a6ahoe

**Comment by emperorstarfinder** [comment]
Will take a look in just a few minutes :) it should build correctly.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development Work Group Leader
Second Galaxy Development Team

**Comment by LifeGold** [comment]
The problem is that it does not create this file when compiling ( (

**Comment by emperorstarfinder** [comment]
are you on 32 bit or 64 bit windows server?

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development Work Group Leader
Second Galaxy Development Team

**Comment by LifeGold** [comment]
64 bit

**Comment by emperorstarfinder** [comment]
x64 bit prebuilt version for windows at: http://virtual-planets.org/downloads/virtual_universe_Win64.zip

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development Work Group Leader
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
Closing as user indicates this now works correct in IRC

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development Work Group Leader
Second Galaxy Development Team
