### ISSUE TITLE
Currency

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#15]
Does not work Currency  in the activated configuration.
http://prntscr.com/aard43
http://prntscr.com/aarcpi
http://prntscr.com/aardov
http://prntscr.com/aarpkr

**Comment by emperorstarfinder** [comment]
The ability to purchase in-world currency or regions is not implemented in BaseCurrency.  This will be done in our incoming AdvancedCurrency and is not likely to be a part of the Core Virtual Universe but will be provided as an optional module due to legal concerns.

Emperor Starfinder
CEO/ Founder
Work Group leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment]
And when approximately it will be done?

**Comment by emperorstarfinder** [comment]
I would imagine in the next few days, however Noah will have a better idea on time frame.  As with all code we do not push it to the github master without internal testing first to be sure it is working the way we want it to work.

Emperor Starfinder
CEO/ Founder
Work Group leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by NoahStarfinder** [comment]
It should work if you have the economy = http:///ServerHostname:8009 set correctly in your GridInfoService.ini. The thing to note here is BaseCurrency is not meant to be a full fledged currency service where you can use a real world currency processor such as Paypal to process payments for purchases of in-world currency and regions.  This will be in the Optional Module for AdvancedCurrency but will not be in the core of Virtual Universe as @emperorstarfinder has indicated.

 Noah Starfinder
 Core Developer
 In-Galaxy Services and Features Developer
 Work Group Member
 Grid Architecture Development Work Group
 Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
See Issue #18 relating to the ProductInfo() error in currency.

**Comment by emperorstarfinder** [comment]
Closing this as this appears to be a resolved matter.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
