### ISSUE TITLE
Time zone

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#19]
How to change the time zone of the server? Or the client , I have shown one hour ahead

**Comment by NoahStarfinder** [comment]
The Time Zone of the server will use the time zone of the host server.  So
if the hosting provider has your host server in a data center in a
different time zone as you then unfortunately the server will see that
time used by the system operating system.

The viewer is hard coded unfortunately and will always give the time
inworld as that of Pacific Standard Time (US)


-- 
Noah Starfinder
Core Developer
In-Galaxy Services and Features Developer
Grid Architecture Development Work Group Member
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
Closing as this has been answered

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
