### ISSUE TITLE
[question] Give at time a viewer for VU ?

### ISSUE THREAD

**Issue by BogusCurry** [Virtual-Universe/Virtual-Universe#2]
Hello ;D

Give at time a viewer for VU ?

**Comment by emperorstarfinder** [comment]
Good morning,

Currently the viewers that work with Opensim (Firestorm, Singularity, Etc.) will work with Virtual Universe.  This however will change as we start the implementation of the planets.  Virtual-Universe repository is our stable release repository so most of the work is done in the Virtual-Dev repository prior to it arriving in the Virtual-Universe repository.  Please feel free to test and report bugs you find so we can fix them.

Emperor Starfinder
Core Developer / Founder
Chief Executive Officer
Grid Architecture Development Work Group Leader
Second Galaxy Development Team

**Comment by BogusCurry** [comment]
Thanks for you answer ;D

Thats nice, I will test that ;D

**Comment by emperorstarfinder** [comment]
Closing as question has been answered.

Emperor Starfinder
Core Developer / Founder
Chief Executive Officer
Grid Architecture Development Work Group Leader
Second Galaxy Development Team
