### ISSUE TITLE
Compile Ubuntu

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#21]
Here is what says command not found http://prntscr.com/af4s15

**Comment by emperorstarfinder** [comment]
We only compile using the runprebuild.sh  to do the actual building we do that in monodevelop  so follow these steps:

1. Terminal
a. In terminal cd to the directory you have saved Virtual-Universe to. (NOTE: do not build in the same directory as your clone of the repository in case you want to commit changes and do pull requests)

b. run the command ./runprebuild.sh when it asks for information use all the defaults.

c. When it completes the compile process it will ask if you want to build choose the default which is no.

2. Monodevelop

a. in the folder you will see Universe.sln double click it and mono develop will launch and load the files.  

b. When Monodevelop completes loading the files select the Build All option in the build menu.  This will build Virtual Universe.  All build files will be in the VirtualUniverse directory.

A full guide for linux will be available soon.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment]
And you don't have by chance already compiled version for Ubuntu. But, I'd like to know how to compile the year will be((

**Comment by emperorstarfinder** [comment]
sure do have a linux prebuilt version.

http://virtual-planets.org/downloads/VirtualUniverse_Linux_x64.tar.gz

Its a brand new fresh built copy of Virtual Universe within the last few minutes.  It has all the necessary folders.  Every time we release a new version or you build locally all you need to do is copy and replace the bin folder nothing else needs to change.

Users guides for Windows, Linux, and Mac OS X coming shortly.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment]
http://prntscr.com/af730u

**Comment by emperorstarfinder** [comment]
You need to install mono on ubuntu

You can find the necessary information on how to Install mono here: http://www.mono-project.com/docs/getting-started/install/linux/

Also be sure to do sudo apt-get update && sudo apt-get upgrade to make sure you have the latest upgrades for Ubuntu 14.04.4 (Trusty Tahr)

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment]
http://prntscr.com/affdgw

**Comment by emperorstarfinder** [comment]
That means you have something already listening on that port.  usually restarting the operating system will fix that.  the command to restart the host server is sudo reboot in the terminal  that is not an error with Virtual Universe that just means it detected a closed instance likely still listening on the port when its not.  restarting the host server will fix that.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment]
((((( http://prnt.sc/afjxcu

**Comment by emperorstarfinder** [comment]
you should be doing as follows:

cd VirtualUniverse/bin

For Grid:
./Universe.Server.sh 

For Region:
./Universe.sh

That error just essentially means the log file doesnt give access to the console to write so youll want to right click on the log file and select properties and in the permissions tab make sure to give Read and Write permissions.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
User appears to have resolved this issue.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
