### ISSUE TITLE
Web Map

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#28]
Locke doesn't display, just empty land http://prntscr.com/ah9zx8

**Comment by emperorstarfinder** [comment]
It will show empty land on the world map via the website that is normal.  The reason is that you want to keep that clean and there is likely nothing rezzed on the region.  the region service will update the maptile and send that to the world map every so often.  So if there are things rezzed in the region it will eventually show up on the region.

Thanks for the heads up on it showing an incorrect region name on the world map.  We will fix that.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment]
Before that was like in the game((

**Comment by emperorstarfinder** [comment]
Well in a way you want the world map to look crisp and clean so it not showing rezzed prims on the land in a region probably is not a bad thing.

As for the default region name showing in that search on the world map ill have to track that down as it shouldnt show that

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
Did you by chance port in the webui from WhiteCore?  that might be why it says WhiteCore instead of Universe which is what ours says.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment]
No nothing changed is taken from github that this version is now the latest and compiled. He's always there I wrote their names the first day set the server.

**Comment by emperorstarfinder** [comment]
Okay if you could email me a copy of your source code as it looks like the built in webinterface was modified which might be why it gives the incorrect default name in the search box on the world map and I will have a look when i get home from lunch.  Email is emperor@secondgalaxy.com

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment]
Now I finish to make changes to the web interface. And load it up, if you like the new interface, can replace the old to the new, will not be against))

**Comment by emperorstarfinder** [comment]
You can always submit a pull request.  or email the proposed code to me to review for inclusion at emperor@secondgalaxy.com

We love it when our users contribute new things that help improve the architecture for everyone.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
So in tracking down the incorrect default region name in the search box on the worldmap in our builtin webui you provided in picture, I have had no luck thus far in finding the problem.  Ass you can see here:

![screenshot from 2016-03-19 15 45 00](https://cloud.githubusercontent.com/assets/2190078/13900973/cf315f4a-ede9-11e5-9061-d4cee61d8290.png)


The default region name in the search box on the world map is correct for Virtual Universe.

You will find this on line 177 in bin/html/slmapapi.js.  If that says WhiteCore change that to Universe or even RealLife3D and that should fix that.

The design you did on your builtin webui looks great as I checked it to see for myself what your world map was doing.  The regions showing empty land I would not worry about the world map should update the map tiles for your regions over time (usually 24 hours during server running)  If you want to submit that you can certianly fork the repository and then do a commit to your fork of the repository and push it to there.  Then just simply do a pull request.  Or you can also email the modified files to me for review at emperor@secondgalaxy.com.  Remember to explain your proposed changes either in the email with the modified files or in your pull requests so we will know what your proposing.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
I fixed this so this wont be an issue again for anyone thanks LifeGold for pointing this out.  Things like this is what helps to make this an even better architecture.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
