### ISSUE TITLE
WEB SERVER

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#29]
Universe/Modules/Web/html/user_profile.cs

 +using Universe.Framework.Servers.HttpServer.Implementation;
 +using Universe.Framework.Services;
 +using Universe.Framework.Services.ClassHelpers.Profile;
 +using Universe.Framework.Utilities;
 +using Universe.Framework.Services.ClassHelpers.Profile;

Is repeated twice
+using Universe.Framework.Services.ClassHelpers.Profile;

**Comment by emperorstarfinder** [comment]
This issue is now fixed.  Good catch, thanks :)
