### ISSUE TITLE
virtual-planets.org

### ISSUE THREAD

**Issue by RyujinnJakka** [Virtual-Universe/Virtual-Universe#3]
About, News Center  &  Policy Center when clicked does not show in template but displays info on white screen. Also no logo appears.

**Comment by emperorstarfinder** [comment]
Yes those are known issues.  The website is being powered by a new system being developed by the Second Galaxy Development Team so there are known issues still being worked out by the website developer

**Comment by emperorstarfinder** [comment]
Issue fixed.  Also corrected a logo in the builtin webui.  Thanks.
