### ISSUE TITLE
Folder Events

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#31]
In the server folder there is a folder of source event, it may somehow bring something after compile this page was available on the website?

**Comment by emperorstarfinder** [comment]
This one is a bit to vague as I am not sure what your referring to here.

**Comment by emperorstarfinder** [comment]
There are no other unnecessary source folders in the repository other then

Universe.Physics.PhysX (which is being worked on by the physics engine developer and the folder is a place holder at the time being)

Universe.ScriptEngine.Phlox (Which is being worked on by the script engine developer and the folder is a place holder at the time being)

These folders are there intentionally but do not break the build or operation of the servers in any way.
