### ISSUE TITLE
World Map

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#37]
http://prntscr.com/akl7sn

**Comment by emperorstarfinder** [comment]
I have tested this and it appears to be working.  This may be related to a configuration setting.  But will look further tonight when I get home from meetings.

**Comment by emperorstarfinder** [comment]
Updates to OARs and IARs coming within the next couple of days.  There are a few flags missing that we do not yet have.  This may be the cause of this issue.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
Updates to all J2KDecoder services complete.  This should now be fixed.  

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
Closing as there has been no further activity on this and it appears to be fixed in recent commits.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
