### ISSUE TITLE
[FEATURE REQUEST]: New Marketplace Modules

### ISSUE THREAD

**Issue by emperorstarfinder** [Virtual-Universe/Virtual-Universe#38]
Offer two types of marketplace sites connected to the architecture.  

Module 1 should be a old SLExchange style version to cater to grids who do not wish to use Viewer Managed Marketplace (VMM).

Module 2 should be the VIewer Managed Marketplace to stay on par with Second Life (owned by Linden Labs) and Second Galaxy (Owned by the Second Galaxy Development Team)

**Comment by LifeGold** [comment]
when about to wait for version 1,0,3?

**Comment by emperorstarfinder** [comment]
We are still on Version 1.0.2 RC1 with RC2 coming around the end of the week with final Version 1.0.2 Release coming mid June.  Development of Version 1.0.3 will begin after the 1.0.2 Release happens.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
Closing as this has been transferred to Virtual-Dev for inclusion in development of Version 1.0.3
