### ISSUE TITLE
[FEATURE REQUEST]: Implement PhysX Physics Engine

### ISSUE THREAD

**Issue by emperorstarfinder** [Virtual-Universe/Virtual-Universe#40]
Implement the PhysX Physics Engine from Nvidia per discussion in the Second Galaxy Development Team's weekly meeting.

**Comment by emperorstarfinder** [comment]
@QueenStarfinder I sent you an email last night to give you a link given to me by Fly-Man- at WhiteCore to MOSES grid which has the wrappers needed for the operating systems for PhysX.

Emperor Starfinder
CEO/ Founder
Core Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by QueenStarfinder** [comment]
@EmperorStarfinder

Great I got the email this morning and have already pulled everything.  I
will need to do some configurations etc but I have everything needed.


Queen Starfinder
Core Developer
Physics Engine Developer
Grid Architecture Development Work Group Member
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
Closing as this has now been transferred to the Virtual-Dev repository for inclusion in the development of Version 1.0.3
