### ISSUE TITLE
[FEATURE REQUEST]: Add ability to allow users to put the businesses they own in their profile

### ISSUE THREAD

**Issue by emperorstarfinder** [Virtual-Universe/Virtual-Universe#41]
A user sent me an email asking if we would consider adding the ability to allow users to add the name of the businesses they own in-world to their profile.  This also could be a good idea for businesses using the architecture to.

A possibility here is to allow users the ability to create business user accounts that might not have access to all the features of a normal user but would allow them to create content, sell and purchase content, etc.

**Comment by LifeGold** [comment]
Hi, a few updates about to say his opinion. As for me, I think to introduce innovations in the server are now not so, as I say your words, "you must first bring it to mind that there is, and then do have new functions" For example, with version 1.0.3 released market and many other updates and without novovedeny. In that I think will have to make adjustments indecomposable. So I think that introduce additional new features in the server early. Well, or do them separately as additional modules need those who have downloaded and installed. Well this is my personal opinion on this around.

**Comment by emperorstarfinder** [comment]
This feature was actually intended for Version 1.0.2 Release and still may
make it in.  It is posted for 1.0.3 in the event that this feature is not
implemented by the final deadline for Version 1.0.2 Release.

Keep in mind there is a development cycle for each version of Virtual
Universe.  During this cycle development is always happening with new
features being added or corrected or updated and old features no longer
needed or obsolete removed.  The cycle works as follows

- Development (Goes normally from July 5 - Feburary 15)
- RC1 (Goes normally from February 15 through April 15)
- RC2 (Goes normally from April 15 through June 15)
- Release (The official release of the version happens on June 16)

After the release happens the development team takes a couple weeks for
our summer retreat where we discuss what the plan for the next version's
development cycle is.

At any time anyone can request we consider a new feature or submit a pull
request of their own following the template established for submitting the
pull request.

Likewise issues opened should also adhere to and use the template provided
to better help us solve issues and improve the software.

Hope that clarifies how the process words :)

**Comment by emperorstarfinder** [comment]
Closing as we have moved this to the Virtual-Dev repository for inclusion in the development of Version 1.0.3  Commenting on features is always welcome.
