### ISSUE TITLE
Question on SSL

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#51]
As here correctly specify the path to the certificate and where to place it?
;; Path to your HTTPS certificate
https_cert_path = ""

**Comment by emperorstarfinder** [comment]
HTTPS is not used mostly in Virtual Universe, but that does not mean that it cannot be.

https://github.com/Virtual-Universe/Virtual-Universe/blob/master/VirtualUniverse/UniverseDocs/HTTPS.txt

I would have to look to see if this is able to be done for the linux side.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment]
After enabling SSL on the site for a variety not available as the certificate to add and did not understand((

**Comment by emperorstarfinder** [comment]
A lot of the documentation is out of date and is in the process of being updated.  A brand new up to date Virtual Universe User Guide will be coming out shortly (hopefully with the Virtual Universe Version 1.0.2-Release (on June 15, 2016).

For the moment I don't recommend using the HTTPS protocol as it may or may not work properly.  Also if you have current regions online this may affect their ability to connect if you created them prior to implementing HTTPS.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
Closing as this has now been answered.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
