### ISSUE TITLE
Error load OAR

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#52]
http://prntscr.com/b81quc

**Comment by emperorstarfinder** [comment]
It appears you don't have the corrected Scripting.ini

In Config/Sim/Scripting/Scripting.ini youll see a line that says; 

Include-WDNE = Sim/Scripting/DotNetEngine.ini

Change that line to say:

Include-VS = Sim/Scripting/VirtualScript.ini

Then restart the servers.  that should resolve this issue for you

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by LifeGold** [comment]
Thanks works

**Comment by emperorstarfinder** [comment]
Your welcome.

Closing as user reports this is now resolved.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
