### ISSUE TITLE
Save OAR Region

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#54]
If you remember there was a problem with the preservation of regions in the OAR. So after this is fixed, they are saved but alas, not all textures saves and turns the region in a boot in half without textures, before such was not and kept the normal textures.

**Comment by emperorstarfinder** [comment]
We believe this may be related to an issue where the name of the item i.e. texture, object, etc is being changed.  We are working on this.  We believe this issue may be related to that or at least affected by that.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
Closing as this appears to be resolved and no further reporting has been done on this issue.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
