### ISSUE TITLE
Question Registration

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#55]
Hi all. Write a check to your site to php, I was wondering what directories it needs to create normal login. Marketplace Listen

**Comment by emperorstarfinder** [comment]
When completed the new standalone webui will have on central login system for the entire site.  There will also be a marketplace feature added to the builtin webui where all the login calls from the website will already be done.  We expect the marketplace to be done during the development process of Version 1.0.3

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
Closing as this has been answered.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
