### ISSUE TITLE
Error: Unable to locate user_currency_history database table

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#56]
1. http://prntscr.com/bm39u7
2. http://prntscr.com/bm4f4m Writes that there is no such table, which is very strange the server did not create it, If you can write the structure of the database here, I'll add it.

**Comment by emperorstarfinder** [comment]
Problem appears to now be resolved so closing this issue.  Please answer the questions provided when opening new issues.  Thank you.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
