### ISSUE TITLE
Error Land Properties 

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#57]
Yesterday I updated the server and now I can not edit anything
 http://prntscr.com/bmm8gq http://prntscr.com/bmm8xf

**Comment by emperorstarfinder** [comment]
Closing this as issue #58 replaces this.  Please see issue #58 to for further on this issue.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
