### ISSUE TITLE
Error: Land Properties

### ISSUE THREAD

**Issue by emperorstarfinder** [Virtual-Universe/Virtual-Universe#58]
### Steps to reproduce

1. Build from latest master
2. Run Universe.exe
3. Attempt to edit land

### Expected behaviour

Land settings should update to changes made.

### Actual behaviour

Yesterday I updated the server and now I can not edit anything
http://prntscr.com/bmm8gq http://prntscr.com/bmm8xf

### Server configuration

Ubuntu 14.04.4 LTS x64

**Web server:**

Not Applicable

**Database:**

MySQL 

**Virtual Universe version:**

1.0.2 Release (latest repository master)

### Logs

Please make sure that Virtual Universe has made an log-file and include a link to it here

Note: When opening new issues you need to answer these questions that are provided by default. This replaces Issue #57

**Comment by emperorstarfinder** [comment]
Please keep in mind that you must in fact be the owner of the parcel or region in order to edit things in the About Land panel.

**Comment by LifeGold** [comment]
Yes, it is I the standard account which creates the server and who is the owner.

**Comment by emperorstarfinder** [comment]
As has been explained previously you should not really be using the system accounts for normal operations.  System accounts are fallback or sink accounts depending on what the account is for.  Likewise we have limited the abilities of the system users to ensure fraudulent activity cant happen as a means to protect grid operators.  

Fallback type

Governor Universe = Default owner of the Universe Mainland Estate
RealEstate Owner = Fallback owner of a private region when no estate is defined as owner
Banker Universe = A sink account to help maintain proper financial accounting
Marketplace Universe = Will be the default system administrative account for the marketplace

Unless there is a real need for you to use the system users for anything other then what we have intended them to be please use normal user accounts for owning regions, etc.

There have been some recent updates to our libOMV for how land settings are handled by the viewers so it is possible that the viewers are not yet able to handle it because we just have not completed the implementation of these new methods.  Issue #54 may also be affecting this to an extent which we are also working on.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
Closing as this appears to be resolved and there has been no further reporting on this issue.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
