### ISSUE TITLE
Error buy region

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe#59]
### Steps to reproduce

1. When buying a region closed by the client.

**Comment by emperorstarfinder** [comment]
You need to answer all the questions provided when opening the issues.

This however is vague so I must assume you mean when buying land your viewer is crashing.  More information will likely be needed here.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
Closing as this appears resolved and there has been no further reporting on this issue.

Emperor Starfinder
CEO/ Founder
Core Developer
Grid Architecture Development
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
