### ISSUE TITLE
Bake Failur

### ISSUE THREAD

**Issue by RyujinnJakka** [Virtual-Universe/Virtual-Universe#6]
Avatar remains a cloud no matter what is done redoing skin, shape hair etc, On first login no default avatar shape is given to new user. user remains cloud. Only after going back into avatar appearance do the textures load but this is only temporary once you relog same issue applies. System users are the only users that receive a texture less avatar. Yes default inventory is loaded..

**Comment by NoahStarfinder** [comment]
See issue #8 for further on this one.

Noah Starfinder
Core Developer
In-Galaxy Services & Features Developer
Second Galaxy Development Team

**Comment by emperorstarfinder** [comment]
Appears to be fixed so closing.
