### ISSUE TITLE
What difference with whitecore

### ISSUE THREAD

**Issue by johnfelipe** [Virtual-Universe/Virtual-Universe#63]
What difference with https://github.com/WhiteCoreSim/WhiteCore-Dev

Stay alert

**Comment by emperorstarfinder** [comment]
Virtual Universe is the Open Source Project Arm of the Second Galaxy Development Team.  While code from WhiteCore-Sim lives in the base code of Virtual Universe, most of the new features being added into Virtual Universe come directly from the Second Galaxy Development Team's proprietary grid architecture known as GalaxyGrid.  Our implmenetations are optimized and intended for grid use rather then standalone.

greythane is the upstream provider representative for WhiteCore-Sim on the Second Galaxy Development Team, just like I represent the Second Galaxy Development Team when helping out with projects for WhiteCore-Sim.

Emperor Starfinder
Founder
Chief Executive Officer
Core Developer
Governing Body Chair
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
Email: emperor@secondgalaxy.com

**Comment by emperorstarfinder** [comment]
Question has been answered.  Closing.

Emperor Starfinder
Founder
Chief Executive Officer
Core Developer
Governing Body Chair
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
Email: emperor@secondgalaxy.com
