### ISSUE TITLE
Create object failur

### ISSUE THREAD

**Issue by RyujinnJakka** [Virtual-Universe/Virtual-Universe#7]
unable to create objects on newly created regions unless region owner logs in first and creates a prim. no error is given on the matter just the message you do not have permission to rezz objects here, Parcel full blah blah.

**Comment by NoahStarfinder** [comment]
Console log level is set to INFO I assume.  Please use the command: set log level debug and try if it gives an error please post it here so we can have a look.

Noah Starfinder
Core Developer
In-Galaxy Services & Features Developer
Second Galaxy Development Team

**Comment by RyujinnJakka** [comment]
roger

**Comment by emperorstarfinder** [comment]
Appears to be resolved so if there are any further issues please provide the error messages if any and steps you did to produce the issue so we can attempt to reproduce it.
