### ISSUE TITLE
Build Failed Latest Master

### ISSUE THREAD

**Issue by RyujinnJakka** [Virtual-Universe/Virtual-Universe#9]
Errors:

/Universe/trunk/Universe.sln (default targets) ->
(Build target) ->
/Universe/trunk/Universe/ScriptEngine/VirtualScript/Universe.ScriptEngine.VirtualScript.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

        CompilerTools/Converters/CSConverter.cs(167,18): error CS0535: `Universe.ScriptEngine.VirtualScript.CompilerTools.AScriptConverter' does not implement interface member `Universe.ScriptEngine.VirtualScript.CompilerTools.IScriptConverter.Initialize(Universe.ScriptEngine.VirtualScript.CompilerTools.Compiler)'

**Comment by BritanyannStarfinder** [comment]
This has now been fixed in commit 96761f0  Thank you for reporting it.

Britanyann Starfinder
Core Developer
Scripting Engine Developer
Second Galaxy Development Team
